<?php

/**
 * Implementation of hook_init()
 */
function node_demo_init() {
  global $user;
  drupal_add_js(array(
    'node_demo' => array(
      'uid' => $user->uid,
      'roles' => array_values($user->roles),
    )
  ), 'setting');

  drupal_add_js('http://localhost:8080/notifications.js', 'file');
  drupal_add_js('jQuery(document).ready(function () {'.
      'notifications.display(Drupal.settings.node_demo.uid, Drupal.settings.node_demo.roles);'.
      '});',
    'inline');
}

function node_demo_webform_select_options_info() {
  $items = array();
  
  $items['roles'] = array(
    'title' => t('Roles'),
    'options callback' => 'webform_options_roles',
  );
  
  return $items;
  
}

function webform_options_roles($component, $flat, $filter, $arguments) {
  $roles = array_values(user_roles());
  return array_combine($roles, $roles);
}
