<?php

/**
 * Implementation of hook_init()
 */
function node_demo_init() {
  global $user;
  drupal_add_js(array(
    'node_demo' => array(
      'uid' => $user->uid,
      'roles' => array_values($user->roles),
    )
  ), 'setting');
  
  drupal_add_js('jQuery(document).ready(function () {console.log(Drupal.settings.node_demo.roles);});', 'inline');
  
  // Si on souhaite inclure un fichier js :
  // drupal_add_js('misc/collapse.js', 'file');
}

function node_demo_webform_select_options_info() {
  $items = array();
  
  $items['roles'] = array(
    'title' => t('Roles'),
    'options callback' => 'webform_options_roles',
  );
  
  return $items;
  
}

function webform_options_roles($component, $flat, $filter, $arguments) {
  $roles = array_values(user_roles());
  return array_combine($roles, $roles);
}
